name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "apps/docs/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install -g docsify-cli

      - name: Build docs
        run: npx docsify-cli init /apps/docs

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: apps/docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
