name: Docs

on:
  push:
    branches:
      - main
    paths:
      - apps/docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/docsify-action@master
        with:
          github_token: ${{ secrets.GP_TOKEN }}
          dir: "apps/docs"
